name: ngcm
channels:
  - conda-forge
dependencies:
  - python=3.7
  - matplotlib
  - numpy
  - pandas
  - pandas-datareader
  - pip
  - pprofile
  - pyzmq
  - scikit-learn
  - scipy
  - seaborn
  - snakeviz
  - sympy
  - xlrd
